spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:chat
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    open-in-view: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate: debug
    com.study.chatservice: debug
